### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Balinus**
Added a better (?) description in README.md.

### CODE REVIEW

**Comment by Datseris** [comment]
Sure. Should we add that it supports Julia versions 1.6+ as well?

**Comment by Datseris** [comment]
(it does support 1.5, but since 1.6 is new LTS we could go there straight away)

**Comment by Balinus** [comment]
Yes, that's a good idea. :)

**Comment by Balinus** [comment]
I specified 1.5+ since some people might be under the tyranny of an admin. :)

**Pull request merged**
